project:
  type: book

book:
  title: "Introduzione a R"
  subtitle: "Un linguaggio di programmazione libero e gratuito in salsa statistica"
  author: "Marco Biffino"
  date: "2024-02-07"
  page-navigation: true
  chapters:
    - index.qmd
    - 01_free_software.qmd
    - 02_r_project.qmd
    - 03_linguaggio_r.qmd
    - 04_espandibilita.qmd
    - 05_gestione_sessione.qmd
    - 06_online_help.qmd
    


format:
  html:
    theme: cosmo
 
lang: it 
language: 
  it:
    crossref-sec-prefix: "Paragrafo"